apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 10
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker
          imagePullPolicy: Never
          env: 
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: ES_HOST
              value: elasticsearch-es-http
            - name: ES_PASS
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic